os: osx
language: cpp
compiler: clang
before_install:
    - brew update
install:
    - brew install qt5 glew lz4 lzo libusb
    - brew link --force qt5
script:
    - pushd thirdparty/tiff-4.0.3
    - ./configure && make
    - popd
    - cd toonz && mkdir build && cd build
    - cmake ../sources
          -DQT_PATH=/usr/local/Cellar/qt5/5.6.0/lib/
          -DTIFF_INCLUDE_DIR=../../thirdparty/tiff-4.0.3/libtiff/
          -DSUPERLU_INCLUDE_DIR=../../thirdparty/superlu/SuperLU_4.1/include/
    - cmake --build . --config Release
