use cxx_qt_build::CxxQtBuilder;
use qt_build_utils::QtBuild;

fn main() {
    println!("cargo:rustc-link-lib=dylib=GL");
    println!("cargo:rustc-link-lib=dylib=GLEW");
    println!("cargo:rustc-link-lib=dylib=GLU");
    println!("cargo:rustc-link-lib=dylib=glut");
    println!("cargo:rustc-link-lib=dylib=jpeg");
    println!("cargo:rustc-link-lib=dylib=turbojpeg");
    println!("cargo:rustc-link-lib=dylib=lz4");
    println!("cargo:rustc-link-lib=dylib=lzma");
    println!("cargo:rustc-link-lib=dylib=mypaint");
    println!("cargo:rustc-link-lib=dylib=opencv_calib3d");
    println!("cargo:rustc-link-lib=dylib=opencv_core");
    println!("cargo:rustc-link-lib=dylib=opencv_highgui");
    println!("cargo:rustc-link-lib=dylib=opencv_imgproc");
    println!("cargo:rustc-link-lib=dylib=opencv_videoio");
    println!("cargo:rustc-link-lib=dylib=png");
    println!("cargo:rustc-link-lib=dylib=superlu");
    println!("cargo:rustc-link-lib=dylib=z");

    println!("cargo:rustc-link-search=thirdparty/tiff-4.0.3/libtiff/.libs");
    println!("cargo:rustc-link-lib=static:+whole-archive=tiff");
    println!("cargo:rustc-link-lib=static:+whole-archive=Qt5UiTools");

    let qt_modules = vec![
        "Core",
        "Gui",
        "Multimedia",
        "Network",
        "OpenGL",
        "PrintSupport",
        "Script",
        "ScriptTools",
        "SerialPort",
        "Svg",
        "UiTools",
        "Widgets",
        "Xml",
    ]
    .iter()
    .map(|m| String::from(*m))
    .collect();
    let qtbuild = QtBuild::new(qt_modules).unwrap();

    CxxQtBuilder::new()
        .file("src/main.rs")
        .qt_module("Core")
        .qt_module("Gui")
        .qt_module("Multimedia")
        .qt_module("Network")
        .qt_module("OpenGL")
        .qt_module("PrintSupport")
        .qt_module("Script")
        .qt_module("SerialPort")
        .qt_module("Svg")
        // .qt_module("UiTools")
        .qt_module("Widgets")
        .qt_module("Xml")
        .qrc("toonz/sources/toonz/toonz.qrc")
        .qrc("toonz/sources/toonzqt/toonzqt.qrc")
        .qrc("toonz/sources/tnztools/tnztools.qrc")
        .qobject_header("toonz/sources/toonzfarm/include/service.h")
        .qobject_header("toonz/sources/include/tfarmcontroller.h")
        // .qobject_header("toonz/sources/toonzfarm/include/tfarmexecutor.h")
        .qobject_header("toonz/sources/include/tfarmplatforms.h")
        .qobject_header("toonz/sources/toonzfarm/include/tfarmproxy.h")
        .qobject_header("toonz/sources/include/tfarmserver.h")
        // .qobject_header("toonz/sources/include/tfarmtask.h")
        .qobject_header("toonz/sources/toonzfarm/include/tlog.h")
        .qobject_header("toonz/sources/include/tcacheresourcepool.h")
        .qobject_header("toonz/sources/common/tfx/trendererP.h")
        .qobject_header("toonz/sources/stopmotion/stopmotion.h")
        .qobject_header("toonz/sources/stopmotion/stopmotioncontroller.h")
        .qobject_header("toonz/sources/stopmotion/webcam.h")
        .qobject_header("toonz/sources/stopmotion/jpgconverter.h")
        .qobject_header("toonz/sources/stopmotion/canon.h")
        .qobject_header("toonz/sources/stopmotion/stopmotionserial.h")
        .qobject_header("toonz/sources/stopmotion/stopmotionlight.h")
        .qobject_header("toonz/sources/toonz/cameracapturelevelcontrol.h")
        .qobject_header("toonz/sources/toonz/penciltestpopup_qt.h")
        .qobject_header("toonz/sources/toonz/navtageditorpopup.h")
        .qobject_header("toonz/sources/include/tools/imagegrouping.h")
        .qobject_header("toonz/sources/include/tools/screenpicker.h")
        .qobject_header("toonz/sources/include/tools/toolhandle.h")
        .qobject_header("toonz/sources/include/tools/tooloptions.h")
        .qobject_header("toonz/sources/include/tundo.h")
        .qobject_header("toonz/sources/include/tthread.h")
        .qobject_header("toonz/sources/common/tcore/tthreadp.h")
        .qobject_header("toonz/sources/include/tipcsrv.h")
        .qobject_header("toonz/sources/include/tipcsrvP.h")
        .qobject_header("toonz/sources/include/tmsgcore.h")
        .qobject_header("toonz/sources/include/tfunctorinvoker.h")
        .qobject_header("toonz/sources/include/toonz/fullcolorpalette.h")
        .qobject_header("toonz/sources/include/toonz/movierenderer.h")
        .qobject_header("toonz/sources/include/toonz/multimediarenderer.h")
        .qobject_header("toonz/sources/include/toonz/palettecontroller.h")
        .qobject_header("toonz/sources/include/toonz/preferences.h")
        .qobject_header("toonz/sources/include/toonz/scriptbinding_centerline_vectorizer.h")
        .qobject_header("toonz/sources/include/toonz/scriptbinding_files.h")
        .qobject_header("toonz/sources/include/toonz/scriptbinding_image_builder.h")
        .qobject_header("toonz/sources/include/toonz/scriptbinding_image.h")
        .qobject_header("toonz/sources/include/toonz/scriptbinding_level.h")
        .qobject_header("toonz/sources/include/toonz/scriptbinding_outline_vectorizer.h")
        .qobject_header("toonz/sources/include/toonz/scriptbinding_rasterizer.h")
        .qobject_header("toonz/sources/include/toonz/scriptbinding_renderer.h")
        .qobject_header("toonz/sources/include/toonz/scriptbinding_scene.h")
        .qobject_header("toonz/sources/include/toonz/scriptbinding_toonz_raster_converter.h")
        .qobject_header("toonz/sources/include/toonz/scriptbinding.h")
        .qobject_header("toonz/sources/include/toonz/scriptengine.h")
        .qobject_header("toonz/sources/include/toonz/stylemanager.h")
        .qobject_header("toonz/sources/include/toonz/tcenterlinevectorizer.h")
        .qobject_header("toonz/sources/include/toonz/tcolumnhandle.h")
        .qobject_header("toonz/sources/include/toonz/tframehandle.h")
        .qobject_header("toonz/sources/include/toonz/tfxhandle.h")
        .qobject_header("toonz/sources/include/toonz/tobjecthandle.h")
        .qobject_header("toonz/sources/include/toonz/tonionskinmaskhandle.h")
        .qobject_header("toonz/sources/include/toonz/tpalettehandle.h")
        .qobject_header("toonz/sources/include/toonz/tscenehandle.h")
        .qobject_header("toonz/sources/include/toonz/txsheethandle.h")
        .qobject_header("toonz/sources/include/toonz/txshlevel.h")
        .qobject_header("toonz/sources/include/toonz/txshlevelhandle.h")
        .qobject_header("toonz/sources/include/toonz/txshsimplelevel.h")
        .qobject_header("toonz/sources/include/toonz/txshsoundcolumn.h")
        .qobject_header("toonz/sources/include/toonzqt/addfxcontextmenu.h")
        .qobject_header("toonz/sources/include/toonzqt/camerasettingswidget.h")
        .qobject_header("toonz/sources/include/toonzqt/checkbox.h")
        .qobject_header("toonz/sources/include/toonzqt/cleanupcamerasettingswidget.h")
        .qobject_header("toonz/sources/include/toonzqt/colorfield.h")
        .qobject_header("toonz/sources/include/toonzqt/combohistogram.h")
        .qobject_header("toonz/sources/include/toonzqt/doublefield.h")
        .qobject_header("toonz/sources/include/toonzqt/doublepairfield.h")
        .qobject_header("toonz/sources/include/toonzqt/dvdialog.h")
        .qobject_header("toonz/sources/include/toonzqt/dvscrollwidget.h")
        .qobject_header("toonz/sources/include/toonzqt/dvtextedit.h")
        .qobject_header("toonz/sources/include/toonzqt/expressionfield.h")
        .qobject_header("toonz/sources/include/toonzqt/filefield.h")
        .qobject_header("toonz/sources/include/toonzqt/flipconsole.h")
        .qobject_header("toonz/sources/include/toonzqt/framenavigator.h")
        .qobject_header("toonz/sources/include/toonzqt/functionkeyframenavigator.h")
        .qobject_header("toonz/sources/include/toonzqt/functionpanel.h")
        .qobject_header("toonz/sources/include/toonzqt/functionsegmentviewer.h")
        .qobject_header("toonz/sources/include/toonzqt/functionselection.h")
        .qobject_header("toonz/sources/include/toonzqt/functionsheet.h")
        .qobject_header("toonz/sources/include/toonzqt/functiontoolbar.h")
        .qobject_header("toonz/sources/include/toonzqt/functiontreeviewer.h")
        .qobject_header("toonz/sources/include/toonzqt/functionviewer.h")
        .qobject_header("toonz/sources/include/toonzqt/fxhistogramrender.h")
        .qobject_header("toonz/sources/include/toonzqt/fxiconmanager.h")
        .qobject_header("toonz/sources/include/toonzqt/fxschematicscene.h")
        .qobject_header("toonz/sources/include/toonzqt/fxselection.h")
        .qobject_header("toonz/sources/include/toonzqt/fxsettings.h")
        .qobject_header("toonz/sources/include/toonzqt/gutil.h")
        .qobject_header("toonz/sources/include/toonzqt/hexcolornames.h")
        .qobject_header("toonz/sources/include/toonzqt/histogram.h")
        .qobject_header("toonz/sources/include/toonzqt/icongenerator.h")
        .qobject_header("toonz/sources/include/toonzqt/imageutils.h")
        .qobject_header("toonz/sources/include/toonzqt/infoviewer.h")
        .qobject_header("toonz/sources/include/toonzqt/intfield.h")
        .qobject_header("toonz/sources/include/toonzqt/intpairfield.h")
        .qobject_header("toonz/sources/include/toonzqt/keyframenavigator.h")
        .qobject_header("toonz/sources/include/toonzqt/lineedit.h")
        .qobject_header("toonz/sources/include/toonzqt/marksbar.h")
        .qobject_header("toonz/sources/include/toonzqt/menubarcommand.h")
        .qobject_header("toonz/sources/include/toonzqt/paletteviewer.h")
        .qobject_header("toonz/sources/include/toonzqt/paletteviewergui.h")
        .qobject_header("toonz/sources/include/toonzqt/paramfield.h")
        .qobject_header("toonz/sources/include/toonzqt/planeviewer.h")
        .qobject_header("toonz/sources/include/toonzqt/popupbutton.h")
        .qobject_header("toonz/sources/include/toonzqt/schematicviewer.h")
        .qobject_header("toonz/sources/include/toonzqt/screenboard.h")
        .qobject_header("toonz/sources/include/toonzqt/scriptconsole.h")
        .qobject_header("toonz/sources/include/toonzqt/seethroughwindow.h")
        .qobject_header("toonz/sources/include/toonzqt/spectrumfield.h")
        .qobject_header("toonz/sources/include/toonzqt/spreadsheetviewer.h")
        .qobject_header("toonz/sources/include/toonzqt/stageschematicscene.h")
        .qobject_header("toonz/sources/include/toonzqt/studiopaletteviewer.h")
        .qobject_header("toonz/sources/include/toonzqt/styleeditor.h")
        .qobject_header("toonz/sources/include/toonzqt/styleindexlineedit.h")
        .qobject_header("toonz/sources/include/toonzqt/stylenameeditor.h")
        .qobject_header("toonz/sources/include/toonzqt/swatchviewer.h")
        .qobject_header("toonz/sources/include/toonzqt/tabbar.h")
        .qobject_header("toonz/sources/include/toonzqt/tmessageviewer.h")
        .qobject_header("toonz/sources/include/toonzqt/tonecurvefield.h")
        .qobject_header("toonz/sources/include/toonzqt/treemodel.h")
        .qobject_header("toonz/sources/include/toonzqt/tselectionhandle.h")
        .qobject_header("toonz/sources/include/toonzqt/updatechecker.h")
        .qobject_header("toonz/sources/include/toonzqt/validatedchoicedialog.h")
        .qobject_header("toonz/sources/tnztools/controlpointeditortool.h")
        .qobject_header("toonz/sources/tnztools/controlpointselection.h")
        .qobject_header("toonz/sources/tnztools/edittool.h")
        .qobject_header("toonz/sources/tnztools/edittoolgadgets.h")
        .qobject_header("toonz/sources/tnztools/filltool.h")
        .qobject_header("toonz/sources/tnztools/fullcolorbrushtool.h")
        .qobject_header("toonz/sources/tnztools/fullcolorfilltool.h")
        .qobject_header("toonz/sources/tnztools/geometrictool.h")
        .qobject_header("toonz/sources/tnztools/plastictool.h")
        .qobject_header("toonz/sources/tnztools/selectiontool.h")
        .qobject_header("toonz/sources/tnztools/skeletonsubtools.h")
        .qobject_header("toonz/sources/tnztools/tooloptionscontrols.h")
        .qobject_header("toonz/sources/tnztools/toonzrasterbrushtool.h")
        .qobject_header("toonz/sources/tnztools/viewtools.h")
        .qobject_header("toonz/sources/toonz/addfilmstripframespopup.h")
        .qobject_header("toonz/sources/toonz/adjustlevelspopup.h")
        .qobject_header("toonz/sources/toonz/adjustthicknesspopup.h")
        .qobject_header("toonz/sources/toonz/antialiaspopup.h")
        .qobject_header("toonz/sources/toonz/audiorecordingpopup.h")
        .qobject_header("toonz/sources/toonz/autoinputcellnumberpopup.h")
        .qobject_header("toonz/sources/toonz/autolipsyncpopup.h")
        .qobject_header("toonz/sources/toonz/batches.h")
        .qobject_header("toonz/sources/toonz/batchserversviewer.h")
        .qobject_header("toonz/sources/toonz/binarizepopup.h")
        .qobject_header("toonz/sources/toonz/boardsettingspopup.h")
        .qobject_header("toonz/sources/toonz/brightnessandcontrastpopup.h")
        .qobject_header("toonz/sources/toonz/cachefxcommand.h")
        .qobject_header("toonz/sources/toonz/camerasettingspopup.h")
        .qobject_header("toonz/sources/toonz/canvassizepopup.h")
        .qobject_header("toonz/sources/toonz/castviewer.h")
        .qobject_header("toonz/sources/toonz/cleanuppaletteviewer.h")
        .qobject_header("toonz/sources/toonz/cleanuppopup.h")
        .qobject_header("toonz/sources/toonz/cleanuppreview.h")
        .qobject_header("toonz/sources/toonz/cleanupsettingsmodel.h")
        .qobject_header("toonz/sources/toonz/cleanupsettingspane.h")
        .qobject_header("toonz/sources/toonz/cleanupsettingspopup.h")
        .qobject_header("toonz/sources/toonz/cleanupswatch.h")
        .qobject_header("toonz/sources/toonz/colormodelbehaviorpopup.h")
        .qobject_header("toonz/sources/toonz/colormodelviewer.h")
        .qobject_header("toonz/sources/toonz/comboviewerpane.h")
        .qobject_header("toonz/sources/toonz/commandbar.h")
        .qobject_header("toonz/sources/toonz/commandbarpopup.h")
        .qobject_header("toonz/sources/toonz/convertfolderpopup.h")
        .qobject_header("toonz/sources/toonz/convertpopup.h")
        .qobject_header("toonz/sources/toonz/crashhandler.h")
        .qobject_header("toonz/sources/toonz/custompaneleditorpopup.h")
        .qobject_header("toonz/sources/toonz/custompanelmanager.h")
        .qobject_header("toonz/sources/toonz/duplicatepopup.h")
        .qobject_header("toonz/sources/toonz/dvdirtreeview.h")
        .qobject_header("toonz/sources/toonz/dvitemview.h")
        .qobject_header("toonz/sources/toonz/dvwidgets.h")
        .qobject_header("toonz/sources/toonz/exportcameratrackpopup.h")
        .qobject_header("toonz/sources/toonz/exportlevelpopup.h")
        .qobject_header("toonz/sources/toonz/exportpanel.h")
        .qobject_header("toonz/sources/toonz/exportscenepopup.h")
        .qobject_header("toonz/sources/toonz/exportxsheetpdf.h")
        .qobject_header("toonz/sources/toonz/expressionreferencemanager.h")
        .qobject_header("toonz/sources/toonz/filebrowser.h")
        .qobject_header("toonz/sources/toonz/filebrowsermodel.h")
        .qobject_header("toonz/sources/toonz/filebrowserpopup.h")
        .qobject_header("toonz/sources/toonz/fileinfopopup.h")
        .qobject_header("toonz/sources/toonz/filmstrip.h")
        .qobject_header("toonz/sources/toonz/flipbook.h")
        .qobject_header("toonz/sources/toonz/formatsettingspopups.h")
        .qobject_header("toonz/sources/toonz/frameheadgadget.h")
        .qobject_header("toonz/sources/toonz/fxparameditorpopup.h")
        .qobject_header("toonz/sources/toonz/histogrampopup.h")
        .qobject_header("toonz/sources/toonz/historypane.h")
        .qobject_header("toonz/sources/toonz/imageviewer.h")
        .qobject_header("toonz/sources/toonz/insertfxpopup.h")
        .qobject_header("toonz/sources/toonz/layerfooterpanel.h")
        .qobject_header("toonz/sources/toonz/layerheaderpanel.h")
        .qobject_header("toonz/sources/toonz/levelcreatepopup.h")
        .qobject_header("toonz/sources/toonz/levelsettingspopup.h")
        .qobject_header("toonz/sources/toonz/linesfadepopup.h")
        .qobject_header("toonz/sources/toonz/lipsyncpopup.h")
        .qobject_header("toonz/sources/toonz/loadfolderpopup.h")
        .qobject_header("toonz/sources/toonz/locatorpopup.h")
        .qobject_header("toonz/sources/toonz/magpiefileimportpopup.h")
        .qobject_header("toonz/sources/toonz/mainwindow.h")
        .qobject_header("toonz/sources/toonz/matchline.h")
        .qobject_header("toonz/sources/toonz/menubar.h")
        .qobject_header("toonz/sources/toonz/menubarpopup.h")
        .qobject_header("toonz/sources/toonz/meshifypopup.h")
        .qobject_header("toonz/sources/toonz/messagepanel.h")
        .qobject_header("toonz/sources/toonz/ocaio.h")
        .qobject_header("toonz/sources/toonz/onionskinmaskgui.h")
        .qobject_header("toonz/sources/toonz/outputsettingspopup.h")
        .qobject_header("toonz/sources/toonz/overwritepopup.h")
        .qobject_header("toonz/sources/toonz/pane.h")
        .qobject_header("toonz/sources/toonz/pltgizmopopup.h")
        .qobject_header("toonz/sources/toonz/preferencespopup.h")
        .qobject_header("toonz/sources/toonz/previewer.h")
        .qobject_header("toonz/sources/toonz/previewfxmanager.h")
        .qobject_header("toonz/sources/toonz/projectpopup.h")
        .qobject_header("toonz/sources/toonz/psdsettingspopup.h")
        .qobject_header("toonz/sources/toonz/reframepopup.h")
        .qobject_header("toonz/sources/toonz/renumberpopup.h")
        .qobject_header("toonz/sources/toonz/reslist.h")
        .qobject_header("toonz/sources/toonz/ruler.h")
        .qobject_header("toonz/sources/toonz/savepresetpopup.h")
        .qobject_header("toonz/sources/toonz/scanpopup.h")
        .qobject_header("toonz/sources/toonz/scenebrowser.h")
        .qobject_header("toonz/sources/toonz/scenesettingspopup.h")
        .qobject_header("toonz/sources/toonz/sceneviewer.h")
        .qobject_header("toonz/sources/toonz/sceneviewercontextmenu.h")
        .qobject_header("toonz/sources/toonz/scriptconsolepanel.h")
        .qobject_header("toonz/sources/toonz/separatecolorspopup.h")
        .qobject_header("toonz/sources/toonz/separatecolorsswatch.h")
        .qobject_header("toonz/sources/toonz/shortcutpopup.h")
        .qobject_header("toonz/sources/toonz/soundtrackexport.h")
        .qobject_header("toonz/sources/toonz/startuppopup.h")
        .qobject_header("toonz/sources/toonz/styleshortcutswitchablepanel.h")
        .qobject_header("toonz/sources/toonz/svncleanupdialog.h")
        .qobject_header("toonz/sources/toonz/svncommitdialog.h")
        .qobject_header("toonz/sources/toonz/svndeletedialog.h")
        .qobject_header("toonz/sources/toonz/svnlockdialog.h")
        .qobject_header("toonz/sources/toonz/svnlockframerangedialog.h")
        .qobject_header("toonz/sources/toonz/svnpurgedialog.h")
        .qobject_header("toonz/sources/toonz/svnrevertdialog.h")
        .qobject_header("toonz/sources/toonz/svnupdateandlockdialog.h")
        .qobject_header("toonz/sources/toonz/svnupdatedialog.h")
        .qobject_header("toonz/sources/toonz/tapp.h")
        .qobject_header("toonz/sources/toonz/tasksviewer.h")
        .qobject_header("toonz/sources/toonz/testpanel.h")
        .qobject_header("toonz/sources/toonz/timestretchpopup.h")
        .qobject_header("toonz/sources/toonz/toolbar.h")
        .qobject_header("toonz/sources/toonz/tooloptionsshortcutinvoker.h")
        .qobject_header("toonz/sources/toonz/tpanels.h")
        .qobject_header("toonz/sources/toonz/trackerpopup.h")
        .qobject_header("toonz/sources/toonz/vectorguideddrawingpane.h")
        .qobject_header("toonz/sources/toonz/vectorizerpopup.h")
        .qobject_header("toonz/sources/toonz/vectorizerswatch.h")
        .qobject_header("toonz/sources/toonz/versioncontrol.h")
        .qobject_header("toonz/sources/toonz/versioncontroltimeline.h")
        .qobject_header("toonz/sources/toonz/versioncontrolwidget.h")
        .qobject_header("toonz/sources/toonz/viewerpane.h")
        .qobject_header("toonz/sources/toonz/xdtsimportpopup.h")
        .qobject_header("toonz/sources/toonz/xshcellviewer.h")
        .qobject_header("toonz/sources/toonz/xshcolumnviewer.h")
        .qobject_header("toonz/sources/toonz/xsheetviewer.h")
        .qobject_header("toonz/sources/toonz/xshnoteviewer.h")
        .qobject_header("toonz/sources/toonz/xshrowviewer.h")
        .qobject_header("toonz/sources/toonz/xshtoolbar.h")
        .qobject_header("toonz/sources/toonzqt/palettesscanpopup.h")
        .qobject_header("toonz/sources/toonzqt/pluginhost.h")
        .qobject_header("toonz/sources/toonzqt/stageobjectselection.h")
        .qobject_header("toonz/sources/toonzqt/tdockwindows.h")
        .qobject_header("toonz/sources/include/toonzqt/fxschematicnode.h")
        .qobject_header("toonz/sources/include/toonzqt/schematicgroupeditor.h")
        .qobject_header("toonz/sources/include/toonzqt/schematicnode.h")
        .qobject_header("toonz/sources/include/toonzqt/stageschematicnode.h")
        .cc_builder(|cc| {
            cc
            // .opt_level(2)
                .define("LINUX", None)
                .define("TNZ_LITTLE_ENDIAN", "1")
                .define("USE_MESA", None)
                .flag("-w")
                .link_lib_modifier("+whole-archive")
                .includes(qtbuild.include_paths())
                .includes(&[
                    "toonz/sources/include",
                    "toonz/sources/include/tools",
                    "toonz/sources/include/toonz",
                    "toonz/sources/sound",
                    "toonz/sources/toonz",
                    "toonz/sources/toonzfarm",
                    "toonz/sources/toonzfarm/include",
                    "toonz/sources/toonzlib",
                    "toonz/sources/toonzqt",
                ])
                .includes(&[
                    "/usr/include/opencv4",
                    "thirdparty/kiss_fft130",
                    "thirdparty/libmypaint/dist/64/include/libmypaint",
                    "thirdparty/superlu/SuperLU_4.1/include",
                    "thirdparty/tiff-4.0.3/libtiff",
                    "thirdparty/tinyexr",
                ])
                .files([
                    "thirdparty/kiss_fft130/kiss_fft.c",
                    "thirdparty/kiss_fft130/tools/kiss_fftnd.c",
                    // "toonz/sources/image/tzp/avl.c",
                    "toonz/sources/common/twain/ttwain_stateX.c",
                    "toonz/sources/common/twain/ttwain_utilX.c",
                    "toonz/sources/common/twain/ttwain_winX.c",
                    "toonz/sources/common/twain/ttwain_capability.c",
                    "toonz/sources/common/twain/ttwain_conversion.c",
                    "toonz/sources/common/twain/ttwain_error.c",
                    "toonz/sources/common/twain/ttwain_state.c",
                    "toonz/sources/common/twain/ttwain_util.c",
                    "toonz/sources/common/twain/ttwain_win.c",
                    // "toonz/sources/tcomposer/stub.cpp",
                    "toonz/sources/tnztools/inputmanager.cpp",
                    "toonz/sources/tnztools/irontool.cpp",
                    "toonz/sources/toonzqt/stageobjectselection.cpp",
                    "toonz/sources/tnztools/magnettool.cpp",
                    "toonz/sources/toonzqt/stageschematicscene.cpp",
                    "toonz/sources/toonzqt/strokesdata.cpp",
                    "toonz/sources/toonzqt/studiopaletteviewer.cpp",
                    "toonz/sources/toonzqt/styledata.cpp",
                    "toonz/sources/tnztools/morphtool.cpp",
                    "toonz/sources/tnztools/mypainttoonzbrush.cpp",
                    "toonz/sources/toonzqt/styleeditor.cpp",
                    "toonz/sources/toonzqt/styleindexlineedit.cpp",
                    "toonz/sources/tnztools/paintbrushtool.cpp",
                    "toonz/sources/tnztools/pinchtool.cpp",
                    "toonz/sources/tnztools/plastictool.cpp",
                    "toonz/sources/tnztools/plastictool_build.cpp",
                    "toonz/sources/toonzqt/styleselection.cpp",
                    "toonz/sources/tnztools/plastictool_animate.cpp",
                    "toonz/sources/toonzqt/stylenameeditor.cpp",
                    // "toonz/sources/t32bitsrv/t32movmsg.cpp",
                    // "toonz/sources/t32bitsrv/t32fontmsg.cpp",
                    // "toonz/sources/t32bitsrv/t323gpmsg.cpp",
                    // "toonz/sources/t32bitsrv/main.cpp",
                    "toonz/sources/stopmotion/webcam.cpp",
                    "toonz/sources/stopmotion/stopmotionserial.cpp",
                    "toonz/sources/toonzlib/stage.cpp",
                    "toonz/sources/toonzlib/thirdparty.cpp",
                    "toonz/sources/toonzlib/targetcolors.cpp",
                    "toonz/sources/toonz/levelcreatepopup.cpp",
                    "toonz/sources/toonzlib/tonionskinmaskhandle.cpp",
                    "toonz/sources/toonz/levelsettingspopup.cpp",
                    "toonz/sources/toonzlib/toonzfolders.cpp",
                    "toonz/sources/toonzlib/toonzimageutils.cpp",
                    "toonz/sources/toonz/linesfadepopup.cpp",
                    "toonz/sources/toonzlib/tobjecthandle.cpp",
                    "toonz/sources/toonzlib/toonzscene.cpp",
                    "toonz/sources/toonzlib/tnewoutlinevectorize.cpp",
                    "toonz/sources/toonzlib/toutlinevectorizer.cpp",
                    "toonz/sources/toonz/lipsyncpopup.cpp",
                    "toonz/sources/toonz/loadfoldercommand.cpp",
                    "toonz/sources/toonzlib/tpalettehandle.cpp",
                    "toonz/sources/toonzlib/tproject.cpp",
                    "toonz/sources/toonz/locatorpopup.cpp",
                    "toonz/sources/toonzlib/tpinnedrangeset.cpp",
                    "toonz/sources/toonzlib/trasterimageutils.cpp",
                    "toonz/sources/toonz/magpiefileimportpopup.cpp",
                    "toonz/sources/toonzlib/tscenehandle.cpp",
                    "toonz/sources/toonzlib/trastercentroid.cpp",
                    "toonz/sources/toonzlib/tstageobject.cpp",
                    "toonz/sources/toonz/mainwindow.cpp",
                    "toonz/sources/toonz/entry.cpp",
                    "toonz/sources/toonzlib/tstageobjectcmd.cpp",
                    "toonz/sources/toonz/loadfolderpopup.cpp",
                    "toonz/sources/toonzlib/tstageobjectspline.cpp",
                    "toonz/sources/toonz/matchline.cpp",
                    "toonz/sources/toonzlib/tstageobjecttree.cpp",
                    "toonz/sources/toonzlib/tlog.cpp",
                    "toonz/sources/toonz/levelcommand.cpp",
                    "toonz/sources/toonz/matchlinecommand.cpp",
                    "toonz/sources/toonzlib/ttilesaver.cpp",
                    "toonz/sources/toonzlib/tfxhandle.cpp",
                    "toonz/sources/toonzlib/tframehandle.cpp",
                    "toonz/sources/toonz/layerheaderpanel.cpp",
                    "toonz/sources/toonzlib/ttileset.cpp",
                    "toonz/sources/toonz/menubar.cpp",
                    "toonz/sources/toonzlib/textureutils.cpp",
                    "toonz/sources/toonzlib/txshcell.cpp",
                    "toonz/sources/toonz/menubarpopup.cpp",
                    "toonz/sources/toonzlib/txshchildlevel.cpp",
                    "toonz/sources/toonzlib/tvectorimageutils.cpp",
                    "toonz/sources/toonzlib/txshcolumn.cpp",
                    "toonz/sources/toonz/mergecmapped.cpp",
                    "toonz/sources/toonz/mergecolumns.cpp",
                    "toonz/sources/toonzlib/txsheetexpr.cpp",
                    "toonz/sources/toonz/meshifypopup.cpp",
                    "toonz/sources/toonzlib/txsheet.cpp",
                    "toonz/sources/toonzlib/txsheethandle.cpp",
                    "toonz/sources/toonz/layerfooterpanel.cpp",
                    "toonz/sources/toonzlib/texturemanager.cpp",
                    "toonz/sources/toonzlib/tdistort.cpp",
                    "toonz/sources/toonzlib/tcolumnhandle.cpp",
                    "toonz/sources/toonzlib/tcolumnfxset.cpp",
                    "toonz/sources/toonz/kis_tablet_support_win8.cpp",
                    "toonz/sources/toonzlib/tcolumnfx.cpp",
                    "toonz/sources/toonzlib/tcleanupper.cpp",
                    "toonz/sources/toonzlib/txshlevel.cpp",
                    "toonz/sources/toonz/keyframeselection.cpp",
                    // "toonz/sources/toonzlib/tcenterlinevectorizerOld.cpp",
                    "toonz/sources/toonzlib/txshlevelcolumn.cpp",
                    "toonz/sources/toonzlib/tcenterlinetostrokes.cpp",
                    "toonz/sources/toonzlib/tcenterlineskeletonizer.cpp",
                    "toonz/sources/toonzlib/txshnoteset.cpp",
                    "toonz/sources/toonzlib/tcenterlinepolygonizer.cpp",
                    "toonz/sources/toonz/onionskinmaskgui.cpp",
                    "toonz/sources/toonz/outputsettingspopup.cpp",
                    "toonz/sources/toonz/ocaio.cpp",
                    "toonz/sources/toonzlib/xshhandlemanager.cpp",
                    "toonz/sources/toonzlib/vectorizerparameters.cpp",
                    "toonz/sources/toonz/overwritepopup.cpp",
                    "toonz/sources/toonzlib/txshzeraryfxlevel.cpp",
                    "toonz/sources/toonz/ObjectTracker.cpp",
                    "toonz/sources/toonz/pane.cpp",
                    "toonz/sources/toonzlib/txshzeraryfxcolumn.cpp",
                    "toonz/sources/toonzlib/txshsoundtextlevel.cpp",
                    // "toonz/sources/toonz/penciltestpopup.cpp",
                    "toonz/sources/toonz/navtageditorpopup.cpp",
                    "toonz/sources/toonzlib/txshlevelhandle.cpp",
                    "toonz/sources/toonz/penciltestpopup_qt.cpp",
                    "toonz/sources/toonz/moviegenerator.cpp",
                    "toonz/sources/toonzlib/txshsoundtextcolumn.cpp",
                    "toonz/sources/toonzlib/txshsoundcolumn.cpp",
                    "toonz/sources/toonz/metnum.cpp",
                    "toonz/sources/toonzlib/txshsoundlevel.cpp",
                    "toonz/sources/toonz/pltgizmopopup.cpp",
                    "toonz/sources/toonzlib/txshpalettelevel.cpp",
                    "toonz/sources/toonz/predict3d.cpp",
                    "toonz/sources/toonzlib/tcenterlinevectorizer.cpp",
                    "toonz/sources/toonzlib/txshpalettecolumn.cpp",
                    "toonz/sources/toonz/messagepanel.cpp",
                    "toonz/sources/toonzlib/txshmeshcolumn.cpp",
                    "toonz/sources/toonz/previewer.cpp",
                    "toonz/sources/toonzlib/txshsimplelevel.cpp",
                    "toonz/sources/toonzlib/tcenterlinecolors.cpp",
                    "toonz/sources/toonz/preferencespopup.cpp",
                    "toonz/sources/toonzlib/tcenterlineadjustments.cpp",
                    "toonz/sources/toonz/keyframemover.cpp",
                    "toonz/sources/toonz/previewfxmanager.cpp",
                    "toonz/sources/toonz/print.cpp",
                    "toonz/sources/toonzlib/tbinarizer.cpp",
                    "toonz/sources/toonz/projectpopup.cpp",
                    "toonz/sources/toonzlib/stylemanager.cpp",
                    "toonz/sources/toonz/keyframedata.cpp",
                    "toonz/sources/toonzlib/tcamera.cpp",
                    "toonz/sources/toonz/psdsettingspopup.cpp",
                    "toonz/sources/toonz/reframepopup.cpp",
                    "toonz/sources/toonz/rendercommand.cpp",
                    "toonz/sources/toonz/iocommand.cpp",
                    "toonz/sources/toonzlib/strokegenerator.cpp",
                    "toonz/sources/toonzlib/studiopalettecmd.cpp",
                    "toonz/sources/toonz/renumberpopup.cpp",
                    "toonz/sources/toonzlib/stagevisitor.cpp",
                    "toonz/sources/toonzlib/stageplayer.cpp",
                    // "toonz/sources/toonz/inbetweencommand.cpp",
                    "toonz/sources/toonzlib/stageobjectutil.cpp",
                    "toonz/sources/toonzlib/studiopalette.cpp",
                    "toonz/sources/toonzlib/stage2.cpp",
                    "toonz/sources/toonz/imageviewer.cpp",
                    "toonz/sources/toonzlib/skeletonlut.cpp",
                    "toonz/sources/toonzlib/skeleton.cpp",
                    "toonz/sources/toonzlib/scriptengine.cpp",
                    "toonz/sources/toonzlib/scriptbinding_toonz_raster_converter.cpp",
                    "toonz/sources/toonzlib/scriptbinding_scene.cpp",
                    "toonz/sources/toonzlib/scriptbinding_renderer.cpp",
                    "toonz/sources/toonz/historypane.cpp",
                    "toonz/sources/toonzlib/scriptbinding_rasterizer.cpp",
                    "toonz/sources/toonzlib/scriptbinding_outline_vectorizer.cpp",
                    "toonz/sources/toonz/history.cpp",
                    "toonz/sources/toonzlib/scriptbinding_level.cpp",
                    "toonz/sources/toonzlib/scriptbinding_image_builder.cpp",
                    "toonz/sources/toonz/histogrampopup.cpp",
                    "toonz/sources/toonzlib/scriptbinding_image.cpp",
                    // "toonz/sources/toonz/fxschematicnodeselection.cpp",
                    "toonz/sources/toonzlib/scriptbinding_files.cpp",
                    "toonz/sources/toonzlib/scriptbinding_centerline_vectorizer.cpp",
                    "toonz/sources/toonzlib/scriptbinding.cpp",
                    "toonz/sources/toonzlib/sceneresources.cpp",
                    "toonz/sources/toonz/fxparameditorpopup.cpp",
                    "toonz/sources/toonzlib/sceneproperties.cpp",
                    "toonz/sources/toonzlib/scenefx.cpp",
                    "toonz/sources/toonz/frameheadgadget.cpp",
                    "toonz/sources/toonzlib/rasterstrokegenerator.cpp",
                    "toonz/sources/toonz/formatsettingspopups.cpp",
                    "toonz/sources/toonzlib/rasterbrush.cpp",
                    "toonz/sources/toonzlib/preferences.cpp",
                    "toonz/sources/toonz/floatingpanelcommand.cpp",
                    "toonz/sources/toonzlib/plasticdeformerfx.cpp",
                    "toonz/sources/toonzlib/palettecontroller.cpp",
                    "toonz/sources/toonzlib/palettecmd.cpp",
                    "toonz/sources/toonz/ruler.cpp",
                    "toonz/sources/toonzlib/outputproperties.cpp",
                    "toonz/sources/toonzlib/orientation.cpp",
                    "toonz/sources/toonz/insertfxpopup.cpp",
                    "toonz/sources/toonz/runscriptcommand.cpp",
                    "toonz/sources/toonz/savepresetpopup.cpp",
                    "toonz/sources/toonz/flipbook.cpp",
                    "toonz/sources/toonzlib/observer.cpp",
                    "toonz/sources/toonz/filmstripselection.cpp",
                    "toonz/sources/toonz/scanlist.cpp",
                    "toonz/sources/toonzlib/navigationtags.cpp",
                    "toonz/sources/toonzlib/namebuilder.cpp",
                    "toonz/sources/toonz/filmstripcommand.cpp",
                    "toonz/sources/toonzlib/Naa2TlvConverter.cpp",
                    "toonz/sources/toonz/filmstrip.cpp",
                    "toonz/sources/toonzlib/mypaintbrushstyle.cpp",
                    "toonz/sources/toonz/scanpopup.cpp",
                    "toonz/sources/toonzlib/multimediarenderer.cpp",
                    // "toonz/sources/toonz/fileviewerpopup.cpp",
                    "toonz/sources/toonzlib/onionskinmask.cpp",
                    "toonz/sources/toonz/fileselection.cpp",
                    "toonz/sources/toonz/scenebrowser.cpp",
                    "toonz/sources/toonz/filedata.cpp",
                    "toonz/sources/toonz/scenebrowserversioncontrol.cpp",
                    "toonz/sources/toonzlib/movierenderer.cpp",
                    "toonz/sources/toonz/filebrowserversioncontrol.cpp",
                    "toonz/sources/toonz/scenesettingspopup.cpp",
                    "toonz/sources/toonz/filebrowserpopup.cpp",
                    "toonz/sources/toonz/filebrowsermodel.cpp",
                    "toonz/sources/toonz/sceneviewer.cpp",
                    "toonz/sources/toonz/sceneviewercontextmenu.cpp",
                    "toonz/sources/toonzlib/logger.cpp",
                    "toonz/sources/toonz/expressionreferencemanager.cpp",
                    "toonz/sources/toonz/filebrowser.cpp",
                    "toonz/sources/toonzlib/levelupdater.cpp",
                    "toonz/sources/toonz/sceneviewerevents.cpp",
                    "toonz/sources/toonz/exportxsheetpdf.cpp",
                    "toonz/sources/toonzlib/levelset.cpp",
                    "toonz/sources/toonz/exportscenepopup.cpp",
                    "toonz/sources/toonzlib/levelproperties.cpp",
                    "toonz/sources/toonz/scriptconsolepanel.cpp",
                    "toonz/sources/toonzlib/imagestyles.cpp",
                    "toonz/sources/toonzlib/imagepainter.cpp",
                    "toonz/sources/toonz/exportlevelpopup.cpp",
                    "toonz/sources/toonz/exportpanel.cpp",
                    "toonz/sources/toonz/selectionutils.cpp",
                    "toonz/sources/toonz/exportlevelcommand.cpp",
                    "toonz/sources/toonz/separatecolorspopup.cpp",
                    "toonz/sources/toonzlib/imagemanager.cpp",
                    "toonz/sources/toonzlib/imagelocation.cpp",
                    "toonz/sources/toonz/separatecolorsswatch.cpp",
                    "toonz/sources/toonz/exportcameratrackpopup.cpp",
                    "toonz/sources/toonz/shortcutpopup.cpp",
                    "toonz/sources/toonzlib/imagebuilders.cpp",
                    "toonz/sources/toonzlib/ikskeleton.cpp",
                    // "toonz/sources/toonz/dvmimedata.cpp",
                    "toonz/sources/toonz/dvwidgets.cpp",
                    "toonz/sources/toonz/dvdirtreeview.cpp",
                    "toonz/sources/toonzlib/ikjacobian.cpp",
                    "toonz/sources/toonzlib/ikengine.cpp",
                    "toonz/sources/toonzlib/iknode.cpp",
                    "toonz/sources/toonzlib/hook.cpp",
                    "toonz/sources/toonz/duplicatepopup.cpp",
                    "toonz/sources/toonzlib/fxdag.cpp",
                    "toonz/sources/toonz/dvitemview.cpp",
                    "toonz/sources/toonzlib/fxcommand.cpp",
                    "toonz/sources/toonzlib/glrasterpainter.cpp",
                    "toonz/sources/toonzlib/fullcolorpalette.cpp",
                    "toonz/sources/toonz/dummyprocessor.cpp",
                    "toonz/sources/toonzlib/fillutil.cpp",
                    "toonz/sources/toonzlib/fill.cpp",
                    "toonz/sources/toonz/drawingdata.cpp",
                    "toonz/sources/toonz/custompanelmanager.cpp",
                    "toonz/sources/toonzlib/filepathproperties.cpp",
                    "toonz/sources/toonzlib/dpiscale.cpp",
                    "toonz/sources/toonzlib/doubleparamcmd.cpp",
                    "toonz/sources/toonzlib/convert2tlv.cpp",
                    "toonz/sources/toonzlib/columnfan.cpp",
                    "toonz/sources/toonzlib/cleanupparameters.cpp",
                    "toonz/sources/toonzlib/cleanuppalette.cpp",
                    "toonz/sources/toonzlib/cleanupcolorstyles.cpp",
                    "toonz/sources/toonzlib/childstack.cpp",
                    "toonz/sources/toonz/curveio.cpp",
                    "toonz/sources/toonzlib/captureparameters.cpp",
                    "toonz/sources/toonz/crashhandler.cpp",
                    "toonz/sources/toonz/soundtrackexport.cpp",
                    "toonz/sources/toonz/convertpopup.cpp",
                    "toonz/sources/toonzlib/boardsettings.cpp",
                    // "toonz/sources/toonzlib/avicodecrestrictions.cpp",
                    "toonz/sources/toonz/convertfolderpopup.cpp",
                    "toonz/sources/toonzlib/autopos.cpp",
                    "toonz/sources/toonz/commandbarpopup.cpp",
                    "toonz/sources/toonzlib/autoclose.cpp",
                    "toonz/sources/toonz/startuppopup.cpp",
                    "toonz/sources/toonz/commandbar.cpp",
                    "toonz/sources/toonz/custompaneleditorpopup.cpp",
                    "toonz/sources/toonz/comboviewerpane.cpp",
                    "toonz/sources/toonz/columnselection.cpp",
                    "toonz/sources/toonz/columncommand.cpp",
                    // "toonz/sources/toonz/studiopalettecmd.cpp",
                    // "toonz/sources/toonz/studiopaletteviewer.cpp",
                    "toonz/sources/toonz/colormodelbehaviorpopup.cpp",
                    "toonz/sources/toonzlib/autoadjust.cpp",
                    // "toonz/sources/toonz/styledata.cpp",
                    // "toonz/sources/toonz/styleselection.cpp",
                    "toonz/sources/toonz/colormodelviewer.cpp",
                    "toonz/sources/toonz/cleanupswatch.cpp",
                    "toonz/sources/toonz/svnlockframerangedialog.cpp",
                    "toonz/sources/toonz/svnlockdialog.cpp",
                    "toonz/sources/toonz/svnpurgedialog.cpp",
                    "toonz/sources/toonz/svndeletedialog.cpp",
                    "toonz/sources/toonz/svnrevertdialog.cpp",
                    "toonz/sources/toonz/svncommitdialog.cpp",
                    "toonz/sources/toonz/svncleanupdialog.cpp",
                    "toonz/sources/toonz/svnupdateandlockdialog.cpp",
                    "toonz/sources/toonz/subscenecommand.cpp",
                    "toonz/sources/toonz/subcameramanager.cpp",
                    "toonz/sources/toonz/svnupdatedialog.cpp",
                    "toonz/sources/toonz/cleanupsettingspopup.cpp",
                    "toonz/sources/toonz/cleanupsettingspane.cpp",
                    "toonz/sources/toonz/tapp.cpp",
                    "toonz/sources/toonz/cleanupsettingsmodel.cpp",
                    "toonz/sources/toonz/cleanuppreview.cpp",
                    "toonz/sources/toonz/tasksviewer.cpp",
                    "toonz/sources/toonz/cleanuppopup.cpp",
                    "toonz/sources/toonz/cleanuppaletteviewer.cpp",
                    "toonz/sources/toonz/cellselectioncommand.cpp",
                    "toonz/sources/toonz/cellselection.cpp",
                    "toonz/sources/toonz/cellkeyframeselection.cpp",
                    "toonz/sources/toonz/testpanel.cpp",
                    "toonz/sources/toonz/tfarmstuff.cpp",
                    "toonz/sources/toonz/cellkeyframedata.cpp",
                    "toonz/sources/toonz/celldata.cpp",
                    "toonz/sources/toonz/styleshortcutswitchablepanel.cpp",
                    "toonz/sources/toonz/castviewer.cpp",
                    "toonz/sources/toonz/castselection.cpp",
                    "toonz/sources/toonz/canvassizepopup.cpp",
                    "toonz/sources/toonz/timestretchpopup.cpp",
                    "toonz/sources/toonz/camerasettingspopup.cpp",
                    "toonz/sources/toonz/toolbar.cpp",
                    "toonz/sources/toonz/tooloptionsshortcutinvoker.cpp",
                    // "toonz/sources/toonz/cameracapturelevelcontrol.cpp",
                    "toonz/sources/toonz/cachefxcommand.cpp",
                    "toonz/sources/toonz/brightnessandcontrastpopup.cpp",
                    "toonz/sources/toonz/boardsettingspopup.cpp",
                    "toonz/sources/toonz/binarizepopup.cpp",
                    "toonz/sources/toonz/batchserversviewer.cpp",
                    "toonz/sources/toonz/batches.cpp",
                    "toonz/sources/toonz/tpanels.cpp",
                    "toonz/sources/toonz/autolipsyncpopup.cpp",
                    "toonz/sources/toonz/trackerpopup.cpp",
                    "toonz/sources/toonz/autoinputcellnumberpopup.cpp",
                    "toonz/sources/toonz/cameracapturelevelcontrol_qt.cpp",
                    "toonz/sources/toonz/audiorecordingpopup.cpp",
                    "toonz/sources/toonz/tvpjson_io.cpp",
                    "toonz/sources/toonz/antialiaspopup.cpp",
                    "toonz/sources/toonz/vcrcommand.cpp",
                    "toonz/sources/toonz/adjustthicknesspopup.cpp",
                    "toonz/sources/toonz/vectorguideddrawingpane.cpp",
                    "toonz/sources/toonz/adjustlevelspopup.cpp",
                    "toonz/sources/toonz/vectorizerpopup.cpp",
                    "toonz/sources/toonz/addfilmstripframespopup.cpp",
                    "toonz/sources/stopmotion/stopmotionlight.cpp",
                    "toonz/sources/tnzbase/trasterfx.cpp",
                    "toonz/sources/stopmotion/stopmotioncontroller.cpp",
                    "toonz/sources/toonz/vectorizerswatch.cpp",
                    "toonz/sources/tnzbase/tfxattributes.cpp",
                    "toonz/sources/tnzbase/texternfx.cpp",
                    "toonz/sources/tnzbase/tfxutil.cpp",
                    "toonz/sources/tnzbase/stringtable.cpp",
                    "toonz/sources/toonz/versioncontrol.cpp",
                    "toonz/sources/tnzbase/permissionsmanager.cpp",
                    "toonz/sources/stopmotion/stopmotion.cpp",
                    "toonz/sources/stopmotion/jpgconverter.cpp",
                    "toonz/sources/stopmotion/canon.cpp",
                    "toonz/sources/tnzext/Types.cpp",
                    "toonz/sources/toonz/versioncontrolwidget.cpp",
                    "toonz/sources/toonz/versioncontroltimeline.cpp",
                    "toonz/sources/tnzext/ttexturesstorage.cpp",
                    "toonz/sources/toonz/versioncontrolxmlreader.cpp",
                    "toonz/sources/tnzext/StrokeStatus.cpp",
                    "toonz/sources/toonz/viewerdraw.cpp",
                    "toonz/sources/tnzext/StrokeDeformationImpl.cpp",
                    // "toonz/sources/tnzext/StrokeDeformationAdapter.cpp",
                    "toonz/sources/toonz/viewerpane.cpp",
                    "toonz/sources/tnzext/StrokeParametricDeformer.cpp",
                    "toonz/sources/tnzext/StrokeDeformation.cpp",
                    "toonz/sources/tnzext/StraightCornerDeformation.cpp",
                    "toonz/sources/toonz/viewerpopup.cpp",
                    "toonz/sources/tnzext/SmoothDeformation.cpp",
                    "toonz/sources/tnzext/SquarePotential.cpp",
                    "toonz/sources/toonz/xdtsimportpopup.cpp",
                    // "toonz/sources/tnzext/SelfLoopDeformation.cpp",
                    "toonz/sources/toonz/xdtsio.cpp",
                    "toonz/sources/tnzext/Potential.cpp",
                    "toonz/sources/tnzext/plasticskeletondeformation.cpp",
                    "toonz/sources/tnzext/plasticskeleton.cpp",
                    "toonz/sources/toonz/xshcellmover.cpp",
                    "toonz/sources/tnzext/plastichandle.cpp",
                    "toonz/sources/tnzext/plasticdeformerstorage.cpp",
                    "toonz/sources/tnzext/plasticdeformer.cpp",
                    "toonz/sources/tnzext/OverallDesigner.cpp",
                    "toonz/sources/tnzext/NotSymmetricExpPotential.cpp",
                    "toonz/sources/tnzext/NotSymmetricBezierPotential.cpp",
                    "toonz/sources/tnzext/meshutils.cpp",
                    "toonz/sources/tnzext/meshtexturizer.cpp",
                    "toonz/sources/tnzext/meshbuilder.cpp",
                    "toonz/sources/toonz/xshcellviewer.cpp",
                    "toonz/sources/tnzext/LinearPotential.cpp",
                    "toonz/sources/tnzext/Selector.cpp",
                    "toonz/sources/toonz/xsheetdragtool.cpp",
                    "toonz/sources/toonz/xsheetcmd.cpp",
                    "toonz/sources/toonz/xsheetviewer.cpp",
                    "toonz/sources/toonz/xshcolumnviewer.cpp",
                    "toonz/sources/tnzext/InterfaceStatus.cpp",
                    "toonz/sources/toonz/xshnoteviewer.cpp",
                    "toonz/sources/tnzext/ExtUtil.cpp",
                    "toonz/sources/tnzext/Readme.cpp",
                    "toonz/sources/toonz/xshrowviewer.cpp",
                    // "toonz/sources/tnzext/DraggerStatus.cpp",
                    "toonz/sources/tnzext/Designer.cpp",
                    "toonz/sources/toonz/xshtoolbar.cpp",
                    "toonz/sources/tnzext/DeformationSelector.cpp",
                    "toonz/sources/tnzext/ContextStatus.cpp",
                    "toonz/sources/tnzext/CornerDeformation.cpp",
                    "toonz/sources/tnzext/CompositeStatus.cpp",
                    "toonz/sources/tnztools/vectortapetool.cpp",
                    "toonz/sources/tnztools/viewtools.cpp",
                    "toonz/sources/tnztools/vectorselectiontool.cpp",
                    "toonz/sources/tnztools/vectorerasertool.cpp",
                    "toonz/sources/tnztools/trackertool.cpp",
                    "toonz/sources/tnztools/typetool.cpp",
                    "toonz/sources/tnztools/track.cpp",
                    "toonz/sources/tnztools/toonzvectorbrushtool.cpp",
                    "toonz/sources/tnztools/toonzrasterbrushtool.cpp",
                    "toonz/sources/tnztools/toolutils.cpp",
                    "toonz/sources/tnztools/tooltimer.cpp",
                    "toonz/sources/tnztools/tooloptionscontrols.cpp",
                    "toonz/sources/tnztools/tooloptions.cpp",
                    "toonz/sources/tnztools/toolhandle.cpp",
                    "toonz/sources/tnztools/tool.cpp",
                    "toonz/sources/toonzqt/validatedchoicedialog.cpp",
                    "toonz/sources/tnztools/stylepicker.cpp",
                    "toonz/sources/tnztools/stylepickertool.cpp",
                    "toonz/sources/toonzqt/updatechecker.cpp",
                    "toonz/sources/tnztools/skeletontool.cpp",
                    "toonz/sources/tnztools/strokeselection.cpp",
                    "toonz/sources/toonzqt/tselectionhandle.cpp",
                    "toonz/sources/toonzqt/trepetitionguard.cpp",
                    "toonz/sources/tnztools/skeletonsubtools.cpp",
                    "toonz/sources/tnztools/shifttracetool.cpp",
                    "toonz/sources/toonzqt/treemodel.cpp",
                    "toonz/sources/tnztools/setsaveboxtool.cpp",
                    "toonz/sources/toonzqt/toonz_params.cpp",
                    "toonz/sources/tnztools/selectiontool.cpp",
                    "toonz/sources/tnztools/screenpicker.cpp",
                    "toonz/sources/toonzqt/tonecurvefield.cpp",
                    "toonz/sources/toonzqt/tmessageviewer.cpp",
                    "toonz/sources/tnztools/rulertool.cpp",
                    "toonz/sources/tnztools/rgbpickertool.cpp",
                    "toonz/sources/toonzqt/tabbar.cpp",
                    "toonz/sources/tnztools/rastertapetool.cpp",
                    "toonz/sources/toonzqt/tdockwindows.cpp",
                    "toonz/sources/tnztools/rasterselectiontool.cpp",
                    "toonz/sources/tnztools/rasterselection.cpp",
                    "toonz/sources/toonzqt/swatchviewer.cpp",
                    "toonz/sources/tnztools/rastererasertool.cpp",
                    "toonz/sources/tnztools/pumptool.cpp",
                    "toonz/sources/tnztools/plastictool_rigidity.cpp",
                    "toonz/sources/tnztools/plastictool_meshedit.cpp",
                    "toonz/sources/toonzqt/stageschematicnode.cpp",
                    "toonz/sources/tnztools/levelselection.cpp",
                    "toonz/sources/tnztools/inputstate.cpp",
                    "toonz/sources/toonzqt/stageobjectsdata.cpp",
                    "toonz/sources/toonzqt/spreadsheetviewer.cpp",
                    "toonz/sources/tnztools/imagegrouping.cpp",
                    "toonz/sources/tnztools/hooktool.cpp",
                    "toonz/sources/tnztools/hookselection.cpp",
                    "toonz/sources/tnztools/geometrictool.cpp",
                    "toonz/sources/toonzqt/spectrumfield.cpp",
                    "toonz/sources/tnztools/fullcolorfilltool.cpp",
                    "toonz/sources/tnztools/fullcolorerasertool.cpp",
                    "toonz/sources/tnztools/fullcolorbrushtool.cpp",
                    "toonz/sources/tnztools/fingertool.cpp",
                    // "toonz/sources/tcomposer/tcomposer.cpp",
                    // "toonz/sources/tcomposer/tests.cpp",
                    "toonz/sources/tnztools/edittoolgadgets.cpp",
                    "toonz/sources/tnztools/filltool.cpp",
                    "toonz/sources/tnztools/edittool.cpp",
                    "toonz/sources/tnztools/editassistantstool.cpp",
                    "toonz/sources/tnztools/cuttertool.cpp",
                    "toonz/sources/tnztools/cursormanager.cpp",
                    "toonz/sources/toonzqt/seethroughwindow.cpp",
                    "toonz/sources/toonzqt/selection.cpp",
                    "toonz/sources/toonzqt/scriptconsole.cpp",
                    "toonz/sources/toonzqt/schematicviewer.cpp",
                    "toonz/sources/toonzqt/screenboard.cpp",
                    "toonz/sources/toonzqt/schematicnode.cpp",
                    "toonz/sources/toonzqt/schematicgroupeditor.cpp",
                    "toonz/sources/tnztools/controlpointselection.cpp",
                    "toonz/sources/toonzqt/rasterimagedata.cpp",
                    "toonz/sources/tnztools/controlpointeditortool.cpp",
                    "toonz/sources/toonzqt/popupbutton.cpp",
                    "toonz/sources/toonzqt/plugin_ui_page_interface.cpp",
                    "toonz/sources/toonzqt/plugin_tile_interface.cpp",
                    "toonz/sources/toonzqt/plugin_port_interface.cpp",
                    "toonz/sources/toonzqt/plugin_param_view_interface.cpp",
                    "toonz/sources/toonzqt/plugin_param_interface.cpp",
                    "toonz/sources/tnztools/bluredbrush.cpp",
                    "toonz/sources/toonzqt/plugin_fxnode_interface.cpp",
                    // "toonz/sources/tconverter/tconverter.cpp",
                    "toonz/sources/tnztools/bendertool.cpp",
                    "toonz/sources/toonzqt/pluginhost.cpp",
                    "toonz/sources/tnztools/autofilltlv.cpp",
                    "toonz/sources/tnztools/autofillpli.cpp",
                    "toonz/sources/toonzqt/planeviewer.cpp",
                    "toonz/sources/toonzqt/pickrgbutils.cpp",
                    "toonz/sources/tnztools/assistant.cpp",
                    "toonz/sources/toonzqt/paramfield.cpp",
                    "toonz/sources/toonzqt/paletteviewergui.cpp",
                    "toonz/sources/toonzqt/paletteviewer.cpp",
                    "toonz/sources/toonzqt/palettesscanpopup.cpp",
                    "toonz/sources/toonzqt/palettedata.cpp",
                    "toonz/sources/toonzqt/menubarcommand.cpp",
                    "toonz/sources/toonzqt/marksbar.cpp",
                    "toonz/sources/toonzqt/lutcalibrator.cpp",
                    "toonz/sources/toonzqt/lineedit.cpp",
                    "toonz/sources/toonzqt/keyframenavigator.cpp",
                    "toonz/sources/toonzqt/intpairfield.cpp",
                    "toonz/sources/toonzqt/intfield.cpp",
                    "toonz/sources/toonzqt/infoviewer.cpp",
                    "toonz/sources/toonzqt/imageutils.cpp",
                    "toonz/sources/toonzqt/icongenerator.cpp",
                    "toonz/sources/toonzqt/histogram.cpp",
                    "toonz/sources/toonzqt/hexcolornames.cpp",
                    "toonz/sources/toonzqt/gutil.cpp",
                    "toonz/sources/toonzqt/fxsettings.cpp",
                    "toonz/sources/toonzqt/fxselection.cpp",
                    "toonz/sources/toonzqt/fxschematicscene.cpp",
                    "toonz/sources/toonzqt/fxschematicnode.cpp",
                    "toonz/sources/toonzqt/fxiconmanager.cpp",
                    "toonz/sources/toonzqt/fxhistogramrender.cpp",
                    "toonz/sources/toonzqt/fxdata.cpp",
                    "toonz/sources/toonzqt/functionviewer.cpp",
                    "toonz/sources/toonzqt/functiontreeviewer.cpp",
                    "toonz/sources/toonzqt/functiontoolbar.cpp",
                    "toonz/sources/toonzqt/functionsheet.cpp",
                    "toonz/sources/toonzqt/functionselection.cpp",
                    "toonz/sources/toonzqt/functionsegmentviewer.cpp",
                    "toonz/sources/toonzqt/functionpaneltools.cpp",
                    "toonz/sources/toonzqt/functionpanel.cpp",
                    "toonz/sources/toonzqt/functionkeyframenavigator.cpp",
                    "toonz/sources/toonzqt/freelayout.cpp",
                    "toonz/sources/toonzqt/framenavigator.cpp",
                    "toonz/sources/toonzqt/flipconsole.cpp",
                    "toonz/sources/toonzqt/filefield.cpp",
                    "toonz/sources/toonzqt/expressionfield.cpp",
                    "toonz/sources/toonzqt/dvtextedit.cpp",
                    "toonz/sources/toonzqt/dvscrollwidget.cpp",
                    "toonz/sources/toonzqt/dvmimedata.cpp",
                    "toonz/sources/toonzqt/dvdialog.cpp",
                    "toonz/sources/toonzqt/doublepairfield.cpp",
                    "toonz/sources/toonzqt/doublefield.cpp",
                    "toonz/sources/toonzqt/dockwidget.cpp",
                    "toonz/sources/toonzqt/docklayout.cpp",
                    "toonz/sources/toonzqt/combohistogram.cpp",
                    "toonz/sources/toonzqt/colorfield.cpp",
                    "toonz/sources/toonzqt/cleanupcamerasettingswidget.cpp",
                    "toonz/sources/toonzqt/checkbox.cpp",
                    "toonz/sources/toonzqt/camerasettingswidget.cpp",
                    "toonz/sources/toonzqt/addfxcontextmenu.cpp",
                    // "toonz/sources/tcleanupper/tcleanupper.cpp",
                    "toonz/sources/tnztools/assistants/guidelineline.cpp",
                    "toonz/sources/tnztools/assistants/guidelineellipse.cpp",
                    "toonz/sources/tnztools/assistants/assistantvanishingpoint.cpp",
                    "toonz/sources/tnztools/assistants/assistantline.cpp",
                    "toonz/sources/tnztools/assistants/assistantellipse.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/YOMBParam.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/YOMBInputParam.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/toonz4_6staff.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/STPic.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/STColSelPic.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/SError.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/SDirection.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/PatternPosition.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/PatternMapParam.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/patternmap.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/Pattern.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/Params.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/InputParam.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/EraseContour.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/CIL.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/CallParam.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/calligraph.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/CallCircle.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/BlurMatrix.cpp",
                    "toonz/sources/toonzlib/sandor_fxs/blend.cpp",
                    "toonz/sources/tnzbase/tscanner/tscannerutil.cpp",
                    "toonz/sources/tnzbase/tscanner/tscannertwain.cpp",
                    "toonz/sources/tnzext/tlin/tlin_superlu_wrap.cpp",
                    "toonz/sources/tnzext/tlin/tlin_cblas_wrap.cpp",
                    "toonz/sources/tnzbase/tscanner/tscannerepson.cpp",
                    "toonz/sources/tnzbase/tscanner/tscanner.cpp",
                    "toonz/sources/tnztools/modifiers/modifiertest.cpp",
                    "toonz/sources/tnztools/modifiers/modifiertangents.cpp",
                    "toonz/sources/tnztools/modifiers/modifiersegmentation.cpp",
                    "toonz/sources/tnztools/modifiers/modifierline.cpp",
                    "toonz/sources/tnztools/modifiers/modifierassistants.cpp",
                    // "toonz/sources/toonzfarm/tfarmclient/dependedlist.cpp",
                    // "toonz/sources/toonzfarm/tfarmclient/thumbnailviewer.cpp",
                    // "toonz/sources/toonzfarm/tfarmclient/thumbnail.cpp",
                    // "toonz/sources/toonzfarm/tfarmclient/util.cpp",
                    // "toonz/sources/toonzfarm/tfarmclient/tgrid.cpp",
                    // "toonz/sources/toonzfarm/tfarmclient/textlist.cpp",
                    // "toonz/sources/toonzfarm/tfarmclient/taskstatuspage.cpp",
                    // "toonz/sources/toonzfarm/tfarmclient/tasks.cpp",
                    // "toonz/sources/toonzfarm/tfarmclient/submitpage.cpp",
                    // "toonz/sources/toonzfarm/tfarmclient/serverstatuspage.cpp",
                    // "toonz/sources/toonzfarm/tfarmclient/scriptconfigpanel.cpp",
                    // "toonz/sources/toonzfarm/tfarmclient/filebrowserpopup.cpp",
                    // "toonz/sources/toonzfarm/tfarmclient/filebrowser.cpp",
                    // "toonz/sources/toonzfarm/tfarmclient/casmsubmitpage.cpp",
                    // "toonz/sources/toonzfarm/tfarmclient/casmfileinfo.cpp",
                    // "toonz/sources/toonzfarm/tfarmclient/casmconfigpanel2.cpp",
                    // "toonz/sources/toonzfarm/tfarmclient/casmconfigpanel.cpp",
                    // "toonz/sources/toonzfarm/tfarmclient/appmainshell.cpp",
                    // "toonz/sources/toonzfarm/tfarmclient/application.cpp",
                    // "toonz/sources/toonzfarm/tfarmserver/tfarmserver_shutdown.cpp",
                    // "toonz/sources/toonzfarm/tfarmserver/tfarmserver.cpp",
                    // "toonz/sources/toonzfarm/tfarmcontroller/tfarmcontroller_shutdown.cpp",
                    // "toonz/sources/toonzfarm/tfarmcontroller/tfarmcontroller.cpp",
                    // "toonz/sources/tnzbase/tscanner/TScannerIO/TUSBScannerIO_W.cpp",
                    "toonz/sources/tnzbase/tscanner/TScannerIO/TUSBScannerIO_M.cpp",
                    //TODO
                    "toonz/sources/toonzfarm/tfarm/ttcpipserver.cpp",
                    "toonz/sources/toonzfarm/tfarm/ttcpipclient.cpp",
                    // "toonz/sources/toonzfarm/tfarm/tserverproxy.cpp",

                    //TODO
                    "toonz/sources/toonzfarm/tfarm/tfarmtask.cpp",
                    // "toonz/sources/toonzfarm/tfarm/tlog.cpp",
                    // "toonz/sources/toonzfarm/tfarm/tfarmserver_c.cpp",
                    // "toonz/sources/toonzfarm/tfarm/tfarmserverstub.cpp",
                    "toonz/sources/toonzfarm/tfarm/tfarmproxy.cpp",
                    "toonz/sources/toonzfarm/tfarm/tfarmexecutor.cpp",
                    "toonz/sources/toonzfarm/tfarm/tfarmcontroller_c.cpp",
                    // "toonz/sources/toonzfarm/tfarm/service.cpp",

                    // "toonz/sources/toonzfarm/tfarm/tbaseserver.cpp",

                    // "toonz/sources/toonzfarm/tnzcore_stuff/tthread.cpp",
                    // "toonz/sources/toonzfarm/tnzcore_stuff/tsystem.cpp",
                    // "toonz/sources/toonzfarm/tnzcore_stuff/tsmartpointer.cpp",
                    // "toonz/sources/toonzfarm/tnzcore_stuff/tfilepath.cpp",
                    "toonz/sources/stdfx/warpfx.cpp",
                    "toonz/sources/stdfx/warp.cpp",
                    "toonz/sources/stdfx/unmultiplyfx.cpp",
                    "toonz/sources/stdfx/tonecurvefx.cpp",
                    "toonz/sources/stdfx/tilefx.cpp",
                    "toonz/sources/stdfx/texturefx.cpp",
                    // "toonz/sources/stdfx/test_boxfx.cpp",
                    "toonz/sources/stdfx/targetspotfx.cpp",
                    "toonz/sources/stdfx/stdfx.cpp",
                    "toonz/sources/stdfx/squaregradientfx.cpp",
                    "toonz/sources/stdfx/solarizefx.cpp",
                    "toonz/sources/stdfx/sharpenfx.cpp",
                    "toonz/sources/stdfx/shadingcontext.cpp",
                    "toonz/sources/stdfx/shaderinterface.cpp",
                    "toonz/sources/stdfx/shaderfx.cpp",
                    "toonz/sources/stdfx/saltpeppernoisefx.cpp",
                    "toonz/sources/stdfx/rotationalblurfx.cpp",
                    "toonz/sources/stdfx/ripplefx.cpp",
                    "toonz/sources/stdfx/rgbmscalefx.cpp",
                    "toonz/sources/stdfx/rgbmfadefx.cpp",
                    "toonz/sources/stdfx/rgbmcutfx.cpp",
                    "toonz/sources/stdfx/rgbkeyfx.cpp",
                    "toonz/sources/stdfx/raylitfx.cpp",
                    "toonz/sources/stdfx/randomwavefx.cpp",
                    "toonz/sources/stdfx/radialblurfx.cpp",
                    "toonz/sources/stdfx/premultiplyfx.cpp",
                    "toonz/sources/stdfx/posterizefx.cpp",
                    "toonz/sources/stdfx/pins.cpp",
                    "toonz/sources/stdfx/perlinnoisefx.cpp",
                    "toonz/sources/stdfx/perlinnoise.cpp",
                    "toonz/sources/stdfx/particlesmanager.cpp",
                    "toonz/sources/stdfx/particlesfx.cpp",
                    "toonz/sources/stdfx/particlesengine.cpp",
                    "toonz/sources/stdfx/particles.cpp",
                    "toonz/sources/stdfx/palettefilterfx.cpp",
                    "toonz/sources/stdfx/nothingfx.cpp",
                    "toonz/sources/stdfx/noisefx.cpp",
                    "toonz/sources/stdfx/multitonefx.cpp",
                    "toonz/sources/stdfx/motionblurfx.cpp",
                    "toonz/sources/stdfx/mosaicfx.cpp",
                    // "toonz/sources/stdfx/magicwandfx.cpp",
                    "toonz/sources/stdfx/localtransparencyfx.cpp",
                    "toonz/sources/stdfx/localblurfx.cpp",
                    "toonz/sources/stdfx/linearwavefx.cpp",
                    "toonz/sources/stdfx/kaleido.cpp",
                    "toonz/sources/stdfx/iwa_timecodefx.cpp",
                    "toonz/sources/stdfx/iwa_tilefx.cpp",
                    "toonz/sources/stdfx/iwa_textfx.cpp",
                    "toonz/sources/stdfx/iwa_tangentflowfx.cpp",
                    "toonz/sources/stdfx/iwa_spingradientfx.cpp",
                    "toonz/sources/stdfx/iwa_spectrumfx.cpp",
                    "toonz/sources/stdfx/iwa_soapbubblefx.cpp",
                    "toonz/sources/stdfx/iwa_simplexnoise.cpp",
                    "toonz/sources/stdfx/iwa_rainbowfx.cpp",
                    "toonz/sources/stdfx/iwa_pnperspectivefx.cpp",
                    "toonz/sources/stdfx/iwa_perspectivedistortfx.cpp",
                    "toonz/sources/stdfx/iwa_particlesmanager.cpp",
                    "toonz/sources/stdfx/iwa_particlesfx.cpp",
                    "toonz/sources/stdfx/iwa_particlesengine.cpp",
                    "toonz/sources/stdfx/iwa_particles.cpp",
                    "toonz/sources/stdfx/iwa_noise1234.cpp",
                    "toonz/sources/stdfx/iwa_motionflowfx.cpp",
                    "toonz/sources/stdfx/iwa_motionblurfx.cpp",
                    "toonz/sources/stdfx/iwa_lineargradientfx.cpp",
                    "toonz/sources/stdfx/iwa_gradientwarpfx.cpp",
                    "toonz/sources/stdfx/iwa_glarefx.cpp",
                    "toonz/sources/stdfx/iwa_flowpaintbrushfx.cpp",
                    "toonz/sources/stdfx/iwa_flowblurfx.cpp",
                    "toonz/sources/stdfx/iwa_floorbumpfx.cpp",
                    "toonz/sources/stdfx/iwa_directionalblurfx.cpp",
                    "toonz/sources/stdfx/iwa_fractalnoisefx.cpp",
                    "toonz/sources/stdfx/iwa_corridorgradientfx.cpp",
                    "toonz/sources/stdfx/iwa_bokeh_util.cpp",
                    "toonz/sources/stdfx/iwa_bokeh_advancedfx.cpp",
                    "toonz/sources/stdfx/iwa_bokehreffx.cpp",
                    "toonz/sources/stdfx/iwa_bokehfx.cpp",
                    "toonz/sources/stdfx/iwa_bloomfx.cpp",
                    "toonz/sources/stdfx/iwa_barreldistortfx.cpp",
                    "toonz/sources/stdfx/iwa_adjustexposurefx.cpp",
                    "toonz/sources/stdfx/ino_warp_hv.cpp",
                    "toonz/sources/stdfx/ino_spin_blur.cpp",
                    "toonz/sources/stdfx/ino_radial_blur.cpp",
                    "toonz/sources/stdfx/ino_pn_clouds.cpp",
                    "toonz/sources/stdfx/ino_negate.cpp",
                    "toonz/sources/stdfx/ino_motion_wind.cpp",
                    "toonz/sources/stdfx/ino_motion_blur.cpp",
                    "toonz/sources/stdfx/ino_median_filter.cpp",
                    "toonz/sources/stdfx/ino_median.cpp",
                    "toonz/sources/stdfx/ino_maxmin.cpp",
                    "toonz/sources/stdfx/ino_line_blur.cpp",
                    "toonz/sources/stdfx/ino_level_rgba.cpp",
                    "toonz/sources/stdfx/ino_level_auto.cpp",
                    "toonz/sources/stdfx/ino_level_master.cpp",
                    "toonz/sources/stdfx/ino_hsv_noise.cpp",
                    "toonz/sources/stdfx/ino_hsv_adjust.cpp",
                    "toonz/sources/stdfx/ino_hls_adjust.cpp",
                    "toonz/sources/stdfx/ino_hls_noise.cpp",
                    "toonz/sources/stdfx/ino_hsv_add.cpp",
                    "toonz/sources/stdfx/ino_hls_add.cpp",
                    "toonz/sources/stdfx/ino_common.cpp",
                    "toonz/sources/stdfx/ino_blur.cpp",
                    "toonz/sources/stdfx/ino_blend_vivid_light.cpp",
                    "toonz/sources/stdfx/ino_blend_subtract.cpp",
                    "toonz/sources/stdfx/ino_density.cpp",
                    "toonz/sources/stdfx/ino_channel_selector.cpp",
                    "toonz/sources/stdfx/ino_blend_soft_light.cpp",
                    "toonz/sources/stdfx/ino_blend_screen.cpp",
                    "toonz/sources/stdfx/ino_blend_pin_light.cpp",
                    "toonz/sources/stdfx/ino_blend_over.cpp",
                    "toonz/sources/stdfx/ino_blend_multiply.cpp",
                    "toonz/sources/stdfx/ino_fog.cpp",
                    "toonz/sources/stdfx/ino_blend_linear_light.cpp",
                    "toonz/sources/stdfx/ino_blend_linear_dodge.cpp",
                    "toonz/sources/stdfx/ino_blend_linear_burn.cpp",
                    "toonz/sources/stdfx/ino_blend_lighter_color.cpp",
                    "toonz/sources/stdfx/ino_blend_hard_light.cpp",
                    "toonz/sources/stdfx/ino_blend_lighten.cpp",
                    "toonz/sources/stdfx/ino_blend_hard_mix.cpp",
                    "toonz/sources/stdfx/ino_blend_darken.cpp",
                    "toonz/sources/stdfx/ino_blend_overlay.cpp",
                    "toonz/sources/stdfx/ino_blend_color_dodge.cpp",
                    "toonz/sources/stdfx/ino_blend_color_burn.cpp",
                    "toonz/sources/stdfx/ino_blend_add.cpp",
                    "toonz/sources/stdfx/igs_warp_vert.cpp",
                    "toonz/sources/stdfx/igs_warp_hori.cpp",
                    "toonz/sources/stdfx/ino_blend_cross_dissolve.cpp",
                    "toonz/sources/stdfx/igs_rotate_blur.cpp",
                    "toonz/sources/stdfx/igs_resource_thread.cpp",
                    "toonz/sources/stdfx/ino_blend_divide.cpp",
                    "toonz/sources/stdfx/igs_resource_sleep.cpp",
                    "toonz/sources/stdfx/igs_resource_multithread.cpp",
                    "toonz/sources/stdfx/igs_resource_msg_from_err.cpp",
                    "toonz/sources/stdfx/igs_radial_blur.cpp",
                    "toonz/sources/stdfx/igs_perlin_noise.cpp",
                    "toonz/sources/stdfx/igs_negate.cpp",
                    "toonz/sources/stdfx/ino_blend_darker_color.cpp",
                    "toonz/sources/stdfx/igs_motion_wind_table.cpp",
                    "toonz/sources/stdfx/igs_motion_wind_pixel.cpp",
                    "toonz/sources/stdfx/igs_motion_wind.cpp",
                    "toonz/sources/stdfx/igs_motion_blur.cpp",
                    "toonz/sources/stdfx/igs_median_filter_smooth.cpp",
                    "toonz/sources/stdfx/igs_median_filter.cpp",
                    "toonz/sources/stdfx/igs_maxmin_slrender.cpp",
                    "toonz/sources/stdfx/igs_maxmin.cpp",
                    "toonz/sources/stdfx/igs_maxmin_lens_matrix.cpp",
                    "toonz/sources/stdfx/igs_math_random.cpp",
                    "toonz/sources/stdfx/igs_line_blur.cpp",
                    "toonz/sources/stdfx/igs_level_auto.cpp",
                    "toonz/sources/stdfx/igs_hsv_noise_in_camera.cpp",
                    "toonz/sources/stdfx/igs_level_auto_in_camera.cpp",
                    "toonz/sources/stdfx/igs_hsv_noise.cpp",
                    "toonz/sources/stdfx/igs_hsv_adjust.cpp",
                    "toonz/sources/stdfx/igs_hsv_add.cpp",
                    "toonz/sources/stdfx/igs_hls_noise_in_camera.cpp",
                    "toonz/sources/stdfx/igs_hls_noise.cpp",
                    "toonz/sources/stdfx/igs_hls_adjust.cpp",
                    "toonz/sources/stdfx/igs_hls_add.cpp",
                    "toonz/sources/stdfx/igs_gauss_distribution.cpp",
                    "toonz/sources/stdfx/igs_gaussian_blur.cpp",
                    "toonz/sources/stdfx/igs_fog.cpp",
                    "toonz/sources/stdfx/igs_density.cpp",
                    "toonz/sources/stdfx/igs_color_rgb_hsv.cpp",
                    "toonz/sources/stdfx/igs_color_rgb_hls.cpp",
                    "toonz/sources/stdfx/igs_color_blend.cpp",
                    "toonz/sources/stdfx/igs_attenuation_distribution.cpp",
                    "toonz/sources/stdfx/hsvutil.cpp",
                    "toonz/sources/stdfx/hsvscalefx.cpp",
                    "toonz/sources/stdfx/hsvkeyfx.cpp",
                    "toonz/sources/stdfx/igs_levels.cpp",
                    "toonz/sources/stdfx/gradients.cpp",
                    "toonz/sources/stdfx/glowfx.cpp",
                    "toonz/sources/stdfx/gammafx.cpp",
                    "toonz/sources/stdfx/freedistortfx.cpp",
                    "toonz/sources/stdfx/fourpointsgradientfx.cpp",
                    "toonz/sources/stdfx/externalpalettefx.cpp",
                    "toonz/sources/stdfx/erodilatefx.cpp",
                    "toonz/sources/stdfx/dissolvefx.cpp",
                    "toonz/sources/stdfx/embossfx.cpp",
                    "toonz/sources/stdfx/despecklefx.cpp",
                    "toonz/sources/stdfx/diamondgradientfx.cpp",
                    "toonz/sources/stdfx/colorembossfx.cpp",
                    "toonz/sources/stdfx/cornerpinfx.cpp",
                    "toonz/sources/stdfx/cloudsfx.cpp",
                    "toonz/sources/stdfx/channelmixerfx.cpp",
                    "toonz/sources/stdfx/changecolorfx.cpp",
                    "toonz/sources/stdfx/calligraphicfx.cpp",
                    "toonz/sources/stdfx/bright_contfx.cpp",
                    "toonz/sources/stdfx/bodyhighlightfx.cpp",
                    "toonz/sources/stdfx/blurfx.cpp",
                    "toonz/sources/stdfx/blendtzfx.cpp",
                    "toonz/sources/stdfx/backlitfx.cpp",
                    // "toonz/sources/stdfx/backlit.cpp",
                    "toonz/sources/stdfx/artcontourfx.cpp",
                    "toonz/sources/stdfx/adjustlevelsfx.cpp",
                    "toonz/sources/sound/tsioutils.cpp",
                    "toonz/sources/sound/tsio.cpp",
                    "toonz/sources/sound/ffmpeg/tsio_ffmpeg.cpp",
                    "toonz/sources/sound/wav/tsio_wav.cpp",
                    "toonz/sources/sound/raw/tsio_raw.cpp",
                    "toonz/sources/sound/mp3/tsio_mp3.cpp",
                    "toonz/sources/sound/aiff/tsio_aiff.cpp",
                    "toonz/sources/colorfx/zigzagstyles.cpp",
                    "toonz/sources/colorfx/strokestyles.cpp",
                    // "toonz/sources/common/xscopedlock.cpp",
                    // "toonz/sources/common/tvectorrenderer.cpp",
                    "toonz/sources/common/tvariant.cpp",
                    "toonz/sources/common/tstringid.cpp",
                    "toonz/sources/common/tproperty.cpp",
                    "toonz/sources/colorfx/regionstyles.cpp",
                    "toonz/sources/common/tmsgcore.cpp",
                    "toonz/sources/colorfx/rasterstyles.cpp",
                    "toonz/sources/colorfx/flowlinestrokestyle.cpp",
                    "toonz/sources/colorfx/colorfxutils.cpp",
                    "toonz/sources/colorfx/colorfx.cpp",
                    "toonz/sources/common/trasterimage/trasterimage.cpp",
                    "toonz/sources/common/trasterimage/tcodec.cpp",
                    // "toonz/sources/common/trasterimage/tcachedlevel.cpp",
                    "toonz/sources/common/trop/trop_borders.cpp",
                    "toonz/sources/common/trop/tropcm.cpp",
                    "toonz/sources/common/trop/trop.cpp",
                    "toonz/sources/common/trop/trgbmscale.cpp",
                    "toonz/sources/common/trop/tresample.cpp",
                    "toonz/sources/common/trop/traylit.cpp",
                    "toonz/sources/common/trop/tover.cpp",
                    "toonz/sources/common/trop/toperators.cpp",
                    "toonz/sources/common/trop/tinvert.cpp",
                    "toonz/sources/common/trop/tfracmove.cpp",
                    "toonz/sources/common/trop/terodilate.cpp",
                    "toonz/sources/common/trop/tdistancetransform.cpp",
                    "toonz/sources/common/trop/tdespeckle.cpp",
                    "toonz/sources/common/trop/tconvolve.cpp",
                    "toonz/sources/common/trop/tconvert.cpp",
                    "toonz/sources/common/trop/tcheckboard.cpp",
                    "toonz/sources/common/trop/tblur.cpp",
                    // "toonz/sources/common/trop/tautoclose.cpp",
                    "toonz/sources/common/trop/tantialias.cpp",
                    "toonz/sources/common/trop/runsmap.cpp",
                    "toonz/sources/common/trop/quickput.cpp",
                    "toonz/sources/common/trop/brush.cpp",
                    "toonz/sources/common/trop/bbox.cpp",
                    "toonz/sources/common/tstream/tstreamexception.cpp",
                    "toonz/sources/common/tstream/tstream.cpp",
                    "toonz/sources/common/tstream/tpersistset.cpp",
                    "toonz/sources/common/tsound/tsound_qt.cpp",
                    // "toonz/sources/common/tsound/tsound_nt.cpp",
                    "toonz/sources/common/tsound/tsound_io.cpp",
                    "toonz/sources/common/tsound/tsound.cpp",
                    "toonz/sources/common/tsound/tsop.cpp",
                    "toonz/sources/common/tsystem/uncpath.cpp",
                    "toonz/sources/common/tsystem/tsystempd.cpp",
                    "toonz/sources/common/tsystem/tsystem.cpp",
                    "toonz/sources/common/tsystem/tpluginmanager.cpp",
                    "toonz/sources/common/tsystem/tlogger.cpp",
                    "toonz/sources/common/tsystem/tfiletype.cpp",
                    "toonz/sources/common/tsystem/tfilepath_io.cpp",
                    "toonz/sources/common/tsystem/tfilepath.cpp",
                    "toonz/sources/common/tsystem/tbigmemorymanager.cpp",
                    "toonz/sources/common/tsystem/cpuextensions.cpp",
                    "toonz/sources/common/tvrender/tvectorbrushstyle.cpp",
                    "toonz/sources/common/tvrender/tvectorbrush.cpp",
                    "toonz/sources/common/tvrender/ttessellator.cpp",
                    "toonz/sources/common/tvrender/tstrokeutil.cpp",
                    "toonz/sources/common/tvrender/tstrokeprop.cpp",
                    "toonz/sources/common/tvrender/tstrokedeformations.cpp",
                    "toonz/sources/common/tvrender/tsimplecolorstyles.cpp",
                    "toonz/sources/common/tvrender/tregionprop.cpp",
                    "toonz/sources/common/tvrender/tpaletteutil.cpp",
                    "toonz/sources/common/tvrender/tpalette.cpp",
                    "toonz/sources/common/tvrender/tofflinegl.cpp",
                    "toonz/sources/common/tvrender/tinbetween.cpp",
                    "toonz/sources/common/tvrender/tglregions.cpp",
                    "toonz/sources/common/tvrender/tglcurves.cpp",
                    "toonz/sources/common/tvrender/tfont_qt.cpp",
                    "toonz/sources/common/tvrender/tellipticbrush.cpp",
                    "toonz/sources/common/tvrender/tcolorstyles.cpp",
                    "toonz/sources/common/tvrender/qtofflinegl.cpp",
                    // "toonz/sources/common/tvrender/macofflinegl.cpp",
                    "toonz/sources/common/ttoonzimage/ttonzimage.cpp",
                    "toonz/sources/common/ttest/ttest.cpp",
                    "toonz/sources/common/tvectorimage/tvectorimage.cpp",
                    "toonz/sources/common/tvectorimage/tsweepboundary.cpp",
                    "toonz/sources/common/tvectorimage/tstrokeoutline.cpp",
                    "toonz/sources/common/tvectorimage/tstroke.cpp",
                    "toonz/sources/common/tvectorimage/tsegmentadjuster.cpp",
                    // "toonz/sources/common/tvectorimage/tregionutil.cpp",
                    "toonz/sources/common/tvectorimage/tregion.cpp",
                    "toonz/sources/common/tvectorimage/tl2lautocloser.cpp",
                    "toonz/sources/common/tvectorimage/tcomputeregions.cpp",
                    "toonz/sources/common/tvectorimage/outlineApproximation.cpp",
                    "toonz/sources/common/tvectorimage/drawutil.cpp",
                    "toonz/sources/common/tvectorimage/cornerdetector.cpp",
                    "toonz/sources/common/tunit/tunit.cpp",
                    "toonz/sources/common/txsheet/tcolumnset.cpp",
                    // "toonz/sources/image/zcc/tiio_zcc.cpp",
                    // "toonz/sources/image/zcc/tfile.cpp",
                    "toonz/sources/common/traster/traster.cpp",
                    "toonz/sources/common/tcontenthistory.cpp",
                    "toonz/sources/common/tparam/ttonecurveparam.cpp",
                    "toonz/sources/common/tparam/tspectrumparam.cpp",
                    "toonz/sources/common/tparam/trangeparam.cpp",
                    "toonz/sources/common/tparam/tpointparam.cpp",
                    "toonz/sources/common/tparam/tpixelparam.cpp",
                    "toonz/sources/common/tparam/tparamset.cpp",
                    "toonz/sources/common/tparam/tparamcontainer.cpp",
                    "toonz/sources/common/tparam/tparam.cpp",
                    "toonz/sources/common/tparam/tnotanimatableparam.cpp",
                    "toonz/sources/common/tparam/tdoubleparamrelayproperty.cpp",
                    "toonz/sources/common/tparam/tdoubleparamfile.cpp",
                    "toonz/sources/common/tparam/tdoubleparam.cpp",
                    "toonz/sources/common/tparam/tdoublekeyframe.cpp",
                    "toonz/sources/common/tparam/tcubicbezier.cpp",
                    "toonz/sources/common/tmetaimage/tmetaimage.cpp",
                    "toonz/sources/common/psdlib/psdutils.cpp",
                    "toonz/sources/common/psdlib/psd.cpp",
                    "toonz/sources/common/tapptools/tparamundo.cpp",
                    "toonz/sources/common/tapptools/tenv.cpp",
                    "toonz/sources/common/tapptools/tcolorutils.cpp",
                    "toonz/sources/common/tapptools/tcli.cpp",
                    "toonz/sources/common/tapptools/tversion.cpp",
                    "toonz/sources/common/tcache/timagecache.cpp",
                    "toonz/sources/common/tcolor/tspectrum.cpp",
                    "toonz/sources/common/tcolor/tpixelutils.cpp",
                    "toonz/sources/common/tcolor/tpixel.cpp",
                    "toonz/sources/common/tcolor/tcolorvalue.cpp",
                    "toonz/sources/common/tcolor/tcolorfunctions.cpp",
                    "toonz/sources/common/tcore/tundo.cpp",
                    // "toonz/sources/common/tcore/tthread_x.cpp",
                    // "toonz/sources/common/tcore/tthread_nt.cpp",
                    "toonz/sources/common/tcore/tthread.cpp",
                    "toonz/sources/common/tcore/tstring.cpp",
                    "toonz/sources/common/tcore/tstopwatch.cpp",
                    "toonz/sources/common/tcore/tsmartpointer.cpp",
                    "toonz/sources/common/tcore/trandom.cpp",
                    "toonz/sources/common/tcore/tmathutil.cpp",
                    "toonz/sources/common/tcore/threadmessage.cpp",
                    "toonz/sources/common/tcore/tfunctorinvoker.cpp",
                    "toonz/sources/common/tcore/texception.cpp",
                    "toonz/sources/common/tcore/tdebugmessage.cpp",
                    "toonz/sources/common/tcore/tdata.cpp",
                    "toonz/sources/common/tfx/zeraryFx.cpp",
                    "toonz/sources/common/tfx/unaryFx.cpp",
                    "toonz/sources/common/tfx/ttzpimagefx.cpp",
                    "toonz/sources/common/tfx/trenderresourcemanager.cpp",
                    "toonz/sources/common/tfx/trenderer.cpp",
                    "toonz/sources/common/tfx/tpredictivecachemanager.cpp",
                    "toonz/sources/common/tfx/tpassivecachemanager.cpp",
                    "toonz/sources/common/tfx/tmacrofx.cpp",
                    "toonz/sources/common/tfx/tfxcachemanager.cpp",
                    "toonz/sources/common/tfx/tfx.cpp",
                    "toonz/sources/common/tfx/tcacheresourcepool.cpp",
                    "toonz/sources/common/tfx/tcacheresource.cpp",
                    "toonz/sources/common/tfx/binaryFx.cpp",
                    "toonz/sources/common/tiio/tiio_std.cpp",
                    "toonz/sources/common/tiio/tiio_jpg_util.cpp",
                    "toonz/sources/common/tiio/tiio_jpg_exif.cpp",
                    "toonz/sources/common/tiio/tiio_jpg.cpp",
                    "toonz/sources/common/tiio/tiio_bmp.cpp",
                    "toonz/sources/common/tiio/tiio.cpp",
                    "toonz/sources/common/tiio/movsettings.cpp",
                    "toonz/sources/common/expressions/ttokenizer.cpp",
                    "toonz/sources/common/expressions/tparser.cpp",
                    "toonz/sources/common/expressions/tgrammar.cpp",
                    "toonz/sources/common/expressions/texpression.cpp",
                    "toonz/sources/common/tgeometry/tgeometry.cpp",
                    "toonz/sources/common/tgeometry/tcurveutil.cpp",
                    "toonz/sources/common/tgeometry/tcurves.cpp",
                    "toonz/sources/common/timage/tlevel.cpp",
                    "toonz/sources/common/timage/timage.cpp",
                    "toonz/sources/common/tgl/tstencilcontrol.cpp",
                    "toonz/sources/common/tgl/tgldisplaylistsmanager.cpp",
                    "toonz/sources/common/tgl/tgl.cpp",
                    "toonz/sources/common/timage_io/tlevel_io.cpp",
                    "toonz/sources/common/timage_io/timage_io.cpp",
                    "toonz/sources/common/tipc/tipcsrv.cpp",
                    "toonz/sources/common/tipc/tipcmsg.cpp",
                    "toonz/sources/common/tipc/tipc.cpp",
                    "toonz/sources/common/tipc/t32bitsrv_wrap.cpp",
                    "toonz/sources/common/tmeshimage/tmeshimage.cpp",
                    "toonz/sources/image/tiio.cpp",
                    "toonz/sources/image/tzm/tiio_tzm.cpp",
                    "toonz/sources/image/tzp/toonzrle.cpp",
                    "toonz/sources/image/tzp/tiio_tzp.cpp",
                    "toonz/sources/image/tzp/tiio_plt.cpp",
                    // "toonz/sources/image/tzp/filetzup.cpp",
                    "toonz/sources/image/png/tiio_png.cpp",
                    "toonz/sources/image/pli/tiio_pli.cpp",
                    "toonz/sources/image/pli/tags.cpp",
                    "toonz/sources/image/pli/pli_io.cpp",
                    "toonz/sources/image/sprite/tiio_sprite.cpp",
                    "toonz/sources/image/psd/tiio_psd.cpp",
                    "toonz/sources/image/svg/tiio_svg.cpp",
                    "toonz/sources/image/quantel/tiio_quantel.cpp",
                    "toonz/sources/image/sgi/filesgi.cpp",
                    "toonz/sources/image/tga/tiio_tga.cpp",
                    "toonz/sources/image/tif/tiio_tif.cpp",
                    "toonz/sources/image/tzl/tiio_tzl.cpp",
                    "toonz/sources/image/mov/tiio_mov_proxy.cpp",
                    // "toonz/sources/image/mov/tiio_movX.cpp",
                    // "toonz/sources/image/mov/tiio_movW.cpp",
                    // "toonz/sources/image/mov/tiio_movM.cpp",
                    // "toonz/sources/image/mov/tiio_movL.cpp",
                    "toonz/sources/image/mesh/tiio_mesh.cpp",
                    "toonz/sources/image/exr/tiio_exr.cpp",
                    "toonz/sources/image/ffmpeg/tiio_webm.cpp",
                    "toonz/sources/image/ffmpeg/tiio_mp4.cpp",
                    "toonz/sources/image/ffmpeg/tiio_gif.cpp",
                    "toonz/sources/image/ffmpeg/tiio_ff_mov.cpp",
                    "toonz/sources/image/ffmpeg/tiio_ffmpeg.cpp",
                    "toonz/sources/image/ffmpeg/tiio_apng.cpp",
                    "toonz/sources/image/3gp/tiio_3gp_proxy.cpp",
                    // "toonz/sources/image/3gp/tiio_3gpW.cpp",
                    "toonz/sources/image/3gp/tiio_3gpM.cpp",
                    // "toonz/sources/image/avi/tiio_avi.cpp",
                    // "toonz/sources/image/bmp/tiio_bmp.cpp",
                    "toonz/sources/image/compatibility/tnz4_cpp.cpp",
                ]);
        })
        .setup_linker()
        .build();
}
